### ISSUE TITLE
Category Type Group Labels are not loaded

### ISSUE THREAD

**Issue by torben-fr** [fgtclb/academic-extensions#128]
## Issue 

Yaml definition for category types of academic programs:
```
groups:
  - identifier: programs
    title: 'LLL:EXT:academic_programs/Resources/Private/Language/locallang_be.xlf:sys_category.programs.group'
    icon: 'EXT:academic_programs/Resources/Public/Icons/CategoryGroups/Programs.svg'
```

Locallang definition in EXT:academic_programs/Resources/Private/Language/locallang_be.xlf:
```
<trans-unit id="sys_category.programs.group">
	<source>Academic Programs</source>
	<target>Akademische Programme</target>
</trans-unit>
```
Screenshot from backend:

<img width="523" alt="Image" src="https://github.com/user-attachments/assets/e7785036-9bb4-41b8-8cff-96a537a05512" />

## Expected behaviour

The group label is visible in the backend
